server:
  port: 8081

spring:
  application:
    name: display

product:
  ribbon:
    listOfServers: localhost:8082

hystrix:
  command:
    productInfo:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 1
        errorThresholdPercentage: 50